package com.example.demo.Model;

public class Campus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.id
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.title
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.tag
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.gmt_create
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.like_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.view_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.comment_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.creator
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.limitation
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private Integer limitation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus.description
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.id
     *
     * @return the value of campus.id
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.id
     *
     * @param id the value for campus.id
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.title
     *
     * @return the value of campus.title
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.title
     *
     * @param title the value for campus.title
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.tag
     *
     * @return the value of campus.tag
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.tag
     *
     * @param tag the value for campus.tag
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.gmt_create
     *
     * @return the value of campus.gmt_create
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.gmt_create
     *
     * @param gmtCreate the value for campus.gmt_create
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.like_count
     *
     * @return the value of campus.like_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.like_count
     *
     * @param likeCount the value for campus.like_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.view_count
     *
     * @return the value of campus.view_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.view_count
     *
     * @param viewCount the value for campus.view_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.comment_count
     *
     * @return the value of campus.comment_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.comment_count
     *
     * @param commentCount the value for campus.comment_count
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.creator
     *
     * @return the value of campus.creator
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.creator
     *
     * @param creator the value for campus.creator
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.limitation
     *
     * @return the value of campus.limitation
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public Integer getLimitation() {
        return limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.limitation
     *
     * @param limitation the value for campus.limitation
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setLimitation(Integer limitation) {
        this.limitation = limitation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus.description
     *
     * @return the value of campus.description
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus.description
     *
     * @param description the value for campus.description
     *
     * @mbg.generated Sat May 23 23:31:00 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}