package com.example.demo.Model;

public class FileSave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filesave.id
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filesave.name
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filesave.key
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filesave.creator
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    private Long creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filesave.id
     *
     * @return the value of filesave.id
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filesave.id
     *
     * @param id the value for filesave.id
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filesave.name
     *
     * @return the value of filesave.name
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filesave.name
     *
     * @param name the value for filesave.name
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filesave.key
     *
     * @return the value of filesave.key
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filesave.key
     *
     * @param key the value for filesave.key
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filesave.creator
     *
     * @return the value of filesave.creator
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filesave.creator
     *
     * @param creator the value for filesave.creator
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }
}