package com.example.demo.Model;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_id
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private Long problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.title
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.create_time
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.view_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.like_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.description
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_id
     *
     * @return the value of problem.problem_id
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public Long getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_id
     *
     * @param problemId the value for problem.problem_id
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.title
     *
     * @return the value of problem.title
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.title
     *
     * @param title the value for problem.title
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.create_time
     *
     * @return the value of problem.create_time
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.create_time
     *
     * @param createTime the value for problem.create_time
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.view_count
     *
     * @return the value of problem.view_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.view_count
     *
     * @param viewCount the value for problem.view_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.like_count
     *
     * @return the value of problem.like_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.like_count
     *
     * @param likeCount the value for problem.like_count
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.description
     *
     * @return the value of problem.description
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.description
     *
     * @param description the value for problem.description
     *
     * @mbg.generated Thu May 14 13:57:28 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}