package com.example.demo.Model;

public class Recommend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.id
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.title
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.tag
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.gmt_create
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.gmt_modified
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.creator
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.view_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.like_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.comment_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.description
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.id
     *
     * @return the value of recommend.id
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.id
     *
     * @param id the value for recommend.id
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.title
     *
     * @return the value of recommend.title
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.title
     *
     * @param title the value for recommend.title
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.tag
     *
     * @return the value of recommend.tag
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.tag
     *
     * @param tag the value for recommend.tag
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.gmt_create
     *
     * @return the value of recommend.gmt_create
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.gmt_create
     *
     * @param gmtCreate the value for recommend.gmt_create
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.gmt_modified
     *
     * @return the value of recommend.gmt_modified
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.gmt_modified
     *
     * @param gmtModified the value for recommend.gmt_modified
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.creator
     *
     * @return the value of recommend.creator
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.creator
     *
     * @param creator the value for recommend.creator
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.view_count
     *
     * @return the value of recommend.view_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.view_count
     *
     * @param viewCount the value for recommend.view_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.like_count
     *
     * @return the value of recommend.like_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.like_count
     *
     * @param likeCount the value for recommend.like_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.comment_count
     *
     * @return the value of recommend.comment_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.comment_count
     *
     * @param commentCount the value for recommend.comment_count
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.description
     *
     * @return the value of recommend.description
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.description
     *
     * @param description the value for recommend.description
     *
     * @mbg.generated Mon May 18 17:03:49 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}