package com.example.demo.Model;

public class Share {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.id
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.title
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.tag
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.gmt_create
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.creator
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.view_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.column_8
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Integer column8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.download_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long downloadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.like_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.comment_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.content
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.id
     *
     * @return the value of share.id
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.id
     *
     * @param id the value for share.id
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.title
     *
     * @return the value of share.title
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.title
     *
     * @param title the value for share.title
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.tag
     *
     * @return the value of share.tag
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.tag
     *
     * @param tag the value for share.tag
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.gmt_create
     *
     * @return the value of share.gmt_create
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.gmt_create
     *
     * @param gmtCreate the value for share.gmt_create
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.creator
     *
     * @return the value of share.creator
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.creator
     *
     * @param creator the value for share.creator
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.view_count
     *
     * @return the value of share.view_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.view_count
     *
     * @param viewCount the value for share.view_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.column_8
     *
     * @return the value of share.column_8
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Integer getColumn8() {
        return column8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.column_8
     *
     * @param column8 the value for share.column_8
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setColumn8(Integer column8) {
        this.column8 = column8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.download_count
     *
     * @return the value of share.download_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.download_count
     *
     * @param downloadCount the value for share.download_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setDownloadCount(Long downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.like_count
     *
     * @return the value of share.like_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.like_count
     *
     * @param likeCount the value for share.like_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.comment_count
     *
     * @return the value of share.comment_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.comment_count
     *
     * @param commentCount the value for share.comment_count
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.content
     *
     * @return the value of share.content
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.content
     *
     * @param content the value for share.content
     *
     * @mbg.generated Mon May 18 13:58:51 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}