package com.example.demo.mapper;

import com.example.demo.Model.FileSave;
import com.example.demo.Model.FileSaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileSaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    long countByExample(FileSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int deleteByExample(FileSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int insert(FileSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int insertSelective(FileSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    List<FileSave> selectByExampleWithRowbounds(FileSaveExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    List<FileSave> selectByExample(FileSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    FileSave selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") FileSave record, @Param("example") FileSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int updateByExample(@Param("record") FileSave record, @Param("example") FileSaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int updateByPrimaryKeySelective(FileSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filesave
     *
     * @mbg.generated Tue May 26 20:59:08 CST 2020
     */
    int updateByPrimaryKey(FileSave record);
}