package com.example.demo.mapper;

import com.example.demo.Model.Share;
import com.example.demo.Model.ShareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    long countByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int deleteByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int insert(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int insertSelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    List<Share> selectByExampleWithBLOBsWithRowbounds(ShareExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    List<Share> selectByExampleWithBLOBs(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    List<Share> selectByExampleWithRowbounds(ShareExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    List<Share> selectByExample(ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    Share selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByExample(@Param("record") Share record, @Param("example") ShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByPrimaryKeySelective(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Share record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbg.generated Wed May 27 23:10:13 CST 2020
     */
    int updateByPrimaryKey(Share record);
}